package response

const (
	ERROR_DBERROR                    string = "ERROR_DATABASE_ERROR"
	ERROR_INTERNAL_ERROR             string = "ERROR_INTERNAL_ERROR"
	ERROR_CANT_REGISTER              string = "ERROR_CANT_REGISTER"
	ERROR_NO_ACCESS_TOKEN            string = "ERROR_NO_ACCESS_TOKEN"
	ERROR_NEED_TO_LOGIN              string = "ERROR_NEED_TO_LOGIN"
	ERROR_WRONG_CONTENT_TYPE         string = "ERROR_WRONG_CONTENT_TYPE"
	ERROR_NO_SUCH_USER               string = "ERROR_NO_SUCH_USER"
	ERROR_NOT_ADMIN                  string = "ERROR_NOT_ADMIN"
	ERROR_USER_NOT_CONFIRMED         string = "ERROR_USER_NOT_CONFIRMED"
	ERROR_USER_BLOCKED               string = "ERROR_USER_BLOCKED"
	ERROR_NO_ANSWER_DATA             string = "ERROR_NO_ANSWER_DATA"
	ERROR_EMAIL_FORMAT               string = "ERROR_EMAIL_FORMAT"
	ERROR_EMAIL_EXISTS               string = "ERROR_EMAIL_EXISTS"
	ERROR_SERVER_UNAVAILABLE         string = "ERROR_SERVER_UNAVAILABLE"
	ERROR_REQUEST_DATA               string = "ERROR_REQUEST_DATA"
	ERROR_TOO_BIG_DATA               string = "ERROR_TOO_BIG_DATA"
	ERROR_EMAIL_WASNT_SENT           string = "ERROR_EMAIL_WASNT_SENT"
	ERROR_TOKEN_NOT_FOUND_OR_EXPIRED string = "ERROR_TOKEN_NOT_FOUND_OR_EXPIRED"
	ERROR_NOT_FOUND                  string = "ERROR_NOT_FOUND"
	ERROR_NO_CONTENT                 string = "ERROR_NO_CONTENT"
)
